name: Deploy to VPS

on:
  push:
    branches:
      - main  # Або master, залежно від того, як називається твоя головна гілка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /stepbystep
            git pull origin main
            # Тут пізніше додамо команди для перезапуску Node.js
